name: Update production database

on:
  push:
    branches:
      - main
    # paths:
    #   - "drizzle/**"
    #   - "schema/**"
  workflow_dispatch:
    inputs: {}
permissions:
  contents: read

concurrency:
  group: update-production-database-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  update-database:
    name: Apply migrations
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Set up Deno
        uses: denoland/setup-deno@v2
      - name: Apply migrations
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: deno task push
